# Generated by Django 4.1.7 on 2025-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutualiste",
            name="nom",
            field=models.CharField(
                help_text="Nom du mutualiste", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="mutualiste",
            name="prenom",
            field=models.CharField(
                help_text="Prénom du mutualiste", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="mutualiste",
            name="sexe",
            field=models.CharField(
                choices=[("M", "Masculin"), ("F", "Féminin")],
                help_text="Sexe du mutualiste",
                max_length=10,
                null=True,
            ),
        ),
    ]
