# Generated by Django 4.1.7 on 2025-01-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0002_mutualiste_nom_mutualiste_prenom_mutualiste_sexe"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiaire",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo du mutualiste",
                null=True,
                upload_to="mutualistes/photos/",
            ),
        ),
    ]
