# Generated by Django 4.1.7 on 2025-01-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0004_mutualiste_mutualistes_numero__6b1981_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiaire",
            name="code_matricule",
            field=models.CharField(
                editable=False,
                help_text="Code matricule généré automatiquement",
                max_length=9,
                null=True,
                unique=True,
            ),
        ),
    ]
