# Generated by Django 4.1.7 on 2025-02-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contrats", "0002_regime_duree_validation_consultation"),
        ("mutualistes", "0005_beneficiaire_code_matricule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mutualisteliste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_contrat",
                    models.CharField(
                        editable=False,
                        help_text="Numéro unique du contrat d'assurance généré automatiquement",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo du mutualiste",
                        null=True,
                        upload_to="mutualistes/photos/",
                    ),
                ),
                (
                    "code_matricule",
                    models.CharField(
                        editable=False,
                        help_text="Code matricule généré automatiquement",
                        max_length=9,
                        unique=True,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom du mutualiste", max_length=100, null=True
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        help_text="Prénom du mutualiste", max_length=100, null=True
                    ),
                ),
                (
                    "date_naissance",
                    models.DateField(help_text="Date de naissance du mutualiste"),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        help_text="Sexe du mutualiste",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "date_adhesion",
                    models.DateField(
                        auto_now_add=True, help_text="Date d'adhésion à l'assurance"
                    ),
                ),
                (
                    "statut",
                    models.BooleanField(
                        default=True, help_text="Statut actif ou inactif"
                    ),
                ),
                (
                    "mutualiste",
                    models.CharField(
                        editable=False,
                        help_text="Code matricule généré automatiquement",
                        max_length=9,
                        unique=True,
                    ),
                ),
                (
                    "type_filiation",
                    models.CharField(
                        choices=[
                            ("adherent", "Adherent"),
                            ("conjoint", "Conjoint"),
                            ("enfant", "Enfant"),
                        ],
                        help_text="Lien de parenté avec le mutualiste",
                        max_length=50,
                    ),
                ),
                (
                    "regime",
                    models.ForeignKey(
                        help_text="Régime d'assurance associé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mutualistesliste",
                        to="contrats.regime",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mutualisteliste",
                "verbose_name_plural": "Mutualistes",
                "ordering": ["numero_contrat"],
            },
        ),
        migrations.AddIndex(
            model_name="mutualisteliste",
            index=models.Index(
                fields=["numero_contrat"], name="mutualistes_numero__f233bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mutualisteliste",
            index=models.Index(
                fields=["code_matricule"], name="mutualistes_code_ma_c6a97e_idx"
            ),
        ),
    ]
