# Generated by Django 4.1.7 on 2025-02-11 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0006_mutualisteliste_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NaturePrestationSociale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        help_text="Nature de la prestation (ex: Scolarité, Médicale, Logement)",
                        max_length=100,
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant de la prestation",
                        max_digits=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrestationSociale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("soumis", "Soumis"),
                            ("validé", "Validé"),
                            ("payé", "Payé"),
                            ("rejeté", "Rejeté"),
                        ],
                        default="soumis",
                        help_text="État de la prestation sociale",
                        max_length=10,
                    ),
                ),
                (
                    "date_soumission",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date de soumission de la demande",
                    ),
                ),
                (
                    "date_validation",
                    models.DateField(
                        blank=True,
                        help_text="Date de validation de la demande",
                        null=True,
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        blank=True,
                        help_text="Date de paiement de la prestation",
                        null=True,
                    ),
                ),
                (
                    "justification",
                    models.FileField(
                        blank=True,
                        help_text="Justification de la prestation sociale",
                        null=True,
                        upload_to="justificatifs/",
                    ),
                ),
                (
                    "preuve_paiement",
                    models.FileField(
                        blank=True,
                        help_text="Fichier justificatif du paiement",
                        null=True,
                        upload_to="preuves_paiement/",
                    ),
                ),
                (
                    "mutualiste",
                    models.ForeignKey(
                        help_text="Mutualiste bénéficiant de la prestation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestations_sociales",
                        to="mutualistes.mutualiste",
                    ),
                ),
                (
                    "prestation_sociale",
                    models.ForeignKey(
                        help_text="Demande de prestation sociale associée",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestationsociale",
                        to="mutualistes.natureprestationsociale",
                    ),
                ),
            ],
        ),
    ]
