# Generated by Django 4.1.7 on 2025-02-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0007_natureprestationsociale_prestationsociale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="natureprestationsociale",
            name="montant",
            field=models.DecimalField(
                decimal_places=0, help_text="Montant de la prestation", max_digits=10
            ),
        ),
    ]
