# Generated by Django 4.1.7 on 2025-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0009_mutualisteliste_observations"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiaire",
            name="observations",
            field=models.CharField(default="R.A.S", max_length=255),
        ),
        migrations.AddField(
            model_name="beneficiaire",
            name="statut",
            field=models.BooleanField(
                default=True, help_text="Statut actif ou inactif"
            ),
        ),
        migrations.AddField(
            model_name="mutualiste",
            name="observations",
            field=models.CharField(default="R.A.S", max_length=255),
        ),
    ]
