# Generated by Django 4.1.7 on 2025-02-19 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contrats", "0003_regime_duree_validation_optique"),
        ("mutualistes", "0010_beneficiaire_observations_beneficiaire_statut_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mutualisteliste",
            options={
                "ordering": ["numero_contrat"],
                "verbose_name": "Mutualiste",
                "verbose_name_plural": "Mutualistes",
            },
        ),
        migrations.AlterField(
            model_name="mutualisteliste",
            name="code_matricule",
            field=models.CharField(
                editable=False,
                help_text="Code matricule unique généré automatiquement",
                max_length=9,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="mutualisteliste",
            name="date_adhesion",
            field=models.DateField(auto_now_add=True, help_text="Date d'adhésion"),
        ),
        migrations.AlterField(
            model_name="mutualisteliste",
            name="date_naissance",
            field=models.DateField(help_text="Date de naissance"),
        ),
        migrations.AlterField(
            model_name="mutualisteliste",
            name="mutualiste",
            field=models.ForeignKey(
                blank=True,
                help_text="Mutualiste principal pour les bénéficiaires",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beneficiaires",
                to="mutualistes.mutualisteliste",
            ),
        ),
        migrations.AlterField(
            model_name="mutualisteliste",
            name="nom",
            field=models.CharField(help_text="Nom", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mutualisteliste",
            name="observations",
            field=models.CharField(
                default="R.A.S", help_text="Observations", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="mutualisteliste",
            name="prenom",
            field=models.CharField(help_text="Prénom", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mutualisteliste",
            name="regime",
            field=models.ForeignKey(
                help_text="Régime d'assurance liste associé",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mutualistesliste",
                to="contrats.regime",
            ),
        ),
        migrations.AlterField(
            model_name="mutualisteliste",
            name="sexe",
            field=models.CharField(
                choices=[("M", "Masculin"), ("F", "Féminin")],
                help_text="Sexe",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mutualisteliste",
            name="type_filiation",
            field=models.CharField(
                choices=[
                    ("adherent", "Adhérent"),
                    ("conjoint", "Conjoint"),
                    ("enfant", "Enfant"),
                ],
                help_text="Lien de parenté",
                max_length=50,
            ),
        ),
    ]
