# Generated by Django 4.1.7 on 2025-02-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0011_alter_mutualisteliste_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiaire",
            name="date_adhesion",
            field=models.DateField(
                auto_now_add=True,
                help_text="Date d'adhésion à l'assurance beneficiaires",
                null=True,
            ),
        ),
    ]
