# Generated by Django 4.1.7 on 2025-02-19 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0012_beneficiaire_date_adhesion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mutualisteliste",
            name="mutualiste",
            field=models.ForeignKey(
                blank=True,
                help_text="Mutualiste principal pour les bénéficiaires",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beneficiairesli",
                to="mutualistes.mutualiste",
            ),
        ),
    ]
