# Generated by Django 4.1.7 on 2025-02-20 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0014_mutualisteliste_beneficiaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mutualisteliste",
            name="mutualiste",
            field=models.ForeignKey(
                help_text="Le mutualiste ayant cette",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listemut",
                to="mutualistes.mutualiste",
            ),
        ),
        migrations.AlterField(
            model_name="mutualisteliste",
            name="numero_contrat",
            field=models.CharField(
                editable=False,
                help_text="Numéro unique du contrat d'assurance généré automatiquement",
                max_length=12,
            ),
        ),
    ]
