# Generated by Django 4.1.7 on 2025-02-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("centres", "0006_centresante_observations"),
        ("mutualistes", "0016_mutualiste_groupe"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutualisteliste",
            name="groupe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diocèseliste",
                to="centres.groupe",
            ),
        ),
    ]
