# Generated by Django 4.1.7 on 2025-02-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0017_mutualisteliste_groupe"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiaire",
            name="telephone",
            field=models.CharField(
                blank=True,
                help_text="Numéro de téléphone de l'utilisateur",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mutualisteliste",
            name="telephone",
            field=models.CharField(
                blank=True,
                help_text="Numéro de téléphone de l'utilisateur",
                max_length=15,
                null=True,
            ),
        ),
    ]
