# Generated by Django 4.1.7 on 2025-02-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0018_beneficiaire_telephone_mutualisteliste_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutualiste",
            name="telephone",
            field=models.CharField(
                blank=True,
                help_text="Numéro de téléphone de l'utilisateur",
                max_length=15,
                null=True,
            ),
        ),
    ]
