# Generated by Django 4.2.19 on 2025-04-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0020_alter_beneficiaire_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiaire",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default/photo.png",
                help_text="Photo du mutualiste",
                null=True,
                upload_to="mutualistes/ayants droits/photos/",
            ),
        ),
        migrations.AlterField(
            model_name="mutualiste",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default/photo.png",
                help_text="Photo du mutualiste",
                null=True,
                upload_to="mutualistes/photos/",
            ),
        ),
        migrations.AlterField(
            model_name="mutualisteliste",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default/photo.png",
                help_text="Photo du mutualiste",
                null=True,
                upload_to="mutualistes/photos/",
            ),
        ),
    ]
