# Generated by Django 4.1.7 on 2024-12-20 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("prestations", "0001_initial"),
        ("centres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="centresanteprestation",
            name="prestation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="centres_associes",
                to="prestations.listedesprestations",
            ),
        ),
        migrations.AddField(
            model_name="centresante",
            name="groupe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="centres_sante",
                to="centres.groupe",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="centresanteprestation",
            unique_together={("centre_sante", "prestation")},
        ),
    ]
