# Generated by Django 4.1.7 on 2025-01-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centres", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centresanteprestation",
            name="tarif_personnalise",
            field=models.IntegerField(
                blank=True,
                help_text="Tarif spécifique pour cette prestation dans ce centre (entier sans virgule).",
                null=True,
            ),
        ),
    ]
