# Generated by Django 4.1.7 on 2025-02-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("centres", "0003_alter_centresanteprestation_tarif_personnalise"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedecinTraitant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(help_text="Nom du médecin", max_length=100)),
                (
                    "prenom",
                    models.CharField(help_text="Prénom du médecin", max_length=100),
                ),
                (
                    "specialite",
                    models.CharField(help_text="Spécialité médicale", max_length=150),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email professionnel du médecin",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        help_text="Numéro de téléphone du médecin", max_length=20
                    ),
                ),
                (
                    "numero_ordre",
                    models.CharField(help_text="ordre du médecin", max_length=25),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date d'enregistrement du médecin"
                    ),
                ),
                (
                    "centre_sante",
                    models.ForeignKey(
                        help_text="Centre de santé où travaille le médecin",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medecins",
                        to="centres.centresante",
                    ),
                ),
            ],
        ),
    ]
