# Generated by Django 4.1.7 on 2025-02-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centres", "0004_medecintraitant"),
    ]

    operations = [
        migrations.AddField(
            model_name="centresante",
            name="statut",
            field=models.BooleanField(
                default=True, help_text="Statut actif ou inactif"
            ),
        ),
    ]
