# Generated by Django 4.2.19 on 2025-03-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utilisateurs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Administrateur"),
                    ("gestionnaire", "Gestionnaire"),
                    ("point_focal", "Point Focal"),
                    ("mutualiste", "Mutualiste"),
                    ("centre_sante", "Centre de Santé"),
                    ("pharmacie", "pharmacie"),
                    ("medecin_conseil", "Médecin Conseil"),
                ],
                default="gestionnaire",
                help_text="Rôle principal de l'utilisateur dans le système",
                max_length=20,
            ),
        ),
    ]
