# Generated by Django 4.1.7 on 2024-12-20 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Regime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom du régime (ex: Régime Général, Régime Spécial)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée du régime",
                        null=True,
                    ),
                ),
                (
                    "taux_couverture",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Taux en % de couverture des frais médicaux (ex: 75.50)",
                        max_digits=5,
                    ),
                ),
                (
                    "tiers_payant",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si le tiers payant est activé pour ce régime",
                    ),
                ),
                (
                    "duree_validation_pharmacie",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Durée de validité en jours pour une prise en charge en pharmacie",
                    ),
                ),
                (
                    "plafond_annuel_couverture",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Plafond annuel de couverture en FCFA (laisser vide pour illimité)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si le régime est actif et peut être utilisé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Régime",
                "verbose_name_plural": "Régimes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Garantie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de la garantie (ex: Hospitalisation, Optique)",
                        max_length=100,
                    ),
                ),
                (
                    "plafond_annuel",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Plafond annuel en FCFA (ex: 100000.00 FCFA)",
                        max_digits=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de la garantie",
                        null=True,
                    ),
                ),
                (
                    "regime",
                    models.ForeignKey(
                        help_text="Régime associé à cette garantie",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garanties",
                        to="contrats.regime",
                    ),
                ),
            ],
            options={
                "verbose_name": "Garantie",
                "verbose_name_plural": "Garanties",
                "ordering": ["regime", "nom"],
                "unique_together": {("regime", "nom")},
            },
        ),
    ]
