# Generated by Django 4.1.7 on 2025-02-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contrats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="regime",
            name="duree_validation_consultation",
            field=models.PositiveIntegerField(
                default=14,
                help_text="Durée de validité en jours pour une prise en charge en consultation",
            ),
        ),
    ]
