# Generated by Django 4.1.7 on 2025-02-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contrats", "0004_alter_garantie_plafond_annuel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="regime",
            name="plafond_adhesion",
            field=models.IntegerField(
                blank=True,
                help_text="Plafond annuel de l'adhésion en FCFA (laisser vide pour illimité)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="regime",
            name="plafond_cotisation_mensuelle",
            field=models.IntegerField(
                blank=True,
                help_text="Plafond annuel de l'adhésion en FCFA (laisser vide pour illimité)",
                null=True,
            ),
        ),
    ]
