# Generated by Django 4.1.7 on 2025-02-23 15:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("centres", "0006_centresante_observations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_cotisation",
                    models.CharField(
                        editable=False,
                        help_text="Numéro unique de la cotisation au format MMYYYY pour chaque groupe",
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "intitule_cotisation",
                    models.CharField(
                        editable=False,
                        help_text="Intitulé de la cotisation sous la forme 'Mois Année'",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        editable=False,
                        help_text="Début de la période de cotisation (1er jour du mois)",
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(
                        editable=False,
                        help_text="Fin de la période de cotisation (dernier jour du mois)",
                    ),
                ),
                (
                    "date_emission",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date à laquelle la cotisation a été émise",
                    ),
                ),
                (
                    "total_adhesion",
                    models.IntegerField(
                        default=0, help_text="Montant total de l'adhésion"
                    ),
                ),
                (
                    "total_cotisation",
                    models.IntegerField(
                        default=0, help_text="Montant total à la charge des mutualistes"
                    ),
                ),
                (
                    "total_general",
                    models.IntegerField(
                        default=0, help_text="Montant total de la facture"
                    ),
                ),
                (
                    "total_payer",
                    models.IntegerField(
                        default=0,
                        help_text="Montant total pris en charge par la mutuelle",
                    ),
                ),
                (
                    "total_restant",
                    models.IntegerField(default=0, help_text="Montant restant à payer"),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        blank=True,
                        help_text="Date de paiement de la facture",
                        null=True,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("payee", "Payée"), ("impayee", "Impayée")],
                        default="impayee",
                        help_text="Statut de la facture (payée ou impayée)",
                        max_length=20,
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        help_text="Groupe émettant la cotisation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotisations",
                        to="centres.groupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotisation",
                "verbose_name_plural": "Cotisations",
                "ordering": ["-date_emission"],
            },
        ),
        migrations.CreateModel(
            name="MouvementPaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.IntegerField(default=0)),
                ("date_paiement", models.DateField(auto_now_add=True)),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[("Espèces", "Espèces"), ("Virement", "Virement")],
                        max_length=50,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fichier_virement",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ordre_paiement/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "cotisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="cotisations.cotisation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cotisation",
            constraint=models.UniqueConstraint(
                fields=("groupe", "numero_cotisation"),
                name="unique_numero_cotisation_par_groupe",
            ),
        ),
        migrations.AddConstraint(
            model_name="cotisation",
            constraint=models.UniqueConstraint(
                fields=("groupe", "intitule_cotisation"),
                name="unique_intitule_cotisation_par_groupe",
            ),
        ),
    ]
