# Generated by Django 4.1.7 on 2024-12-20 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mutualistes", "0001_initial"),
        ("centres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListeDesPrestations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de la prestation médicale", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de la prestation",
                        null=True,
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation Médicale"),
                            ("examen", "Examen Médical"),
                            ("analyse", "Analyse de Laboratoire"),
                            ("soin", "Soin Infirmier"),
                            ("medicament", "Médicament"),
                        ],
                        help_text="Catégorie de la prestation",
                        max_length=20,
                    ),
                ),
                (
                    "tarif_standard",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tarif standard",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True, help_text="Indique si la prestation est active"
                    ),
                ),
                (
                    "soumis_a_validation",
                    models.BooleanField(
                        default=False, help_text="Validation préalable nécessaire ?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Liste des prestations",
                "verbose_name_plural": "Listes des prestations",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Medicament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(help_text="Nom du médicament", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description du médicament", null=True
                    ),
                ),
                (
                    "disponible_en_pharmacie",
                    models.BooleanField(
                        default=True, help_text="Disponible en pharmacie"
                    ),
                ),
                (
                    "cout_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Coût unitaire du médicament",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Médicament",
                "verbose_name_plural": "Médicaments",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="MedicamentUtilise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_servie", models.PositiveIntegerField()),
                ("cout_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Médicament Utilisé",
                "verbose_name_plural": "Médicaments Utilisés",
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicament", models.CharField(max_length=255)),
                ("quantite_prescrite", models.PositiveIntegerField()),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("substitution_possible", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PriseEnCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_prise_en_charge",
                    models.DateField(
                        help_text="Date à laquelle la prise en charge a eu lieu"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de la création du dossier",
                    ),
                ),
                (
                    "numero_dossier",
                    models.CharField(
                        help_text="Numéro unique du dossier de prise en charge, format AAMMDDHHMM",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "duree_validite",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Durée de validité en jours pour cette prise en charge",
                        null=True,
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        help_text="Le centre de santé ayant pris en charge le mutualiste",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prises_en_charge",
                        to="centres.centresante",
                    ),
                ),
                (
                    "mutualiste",
                    models.ForeignKey(
                        help_text="Le mutualiste ayant cette prise en charge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prises_en_charge",
                        to="mutualistes.mutualiste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prise en charge",
                "verbose_name_plural": "Prises en charge",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="PrestationPharmacie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_prestation",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date et heure de la prestation"
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "part_mutualiste",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "part_mutuelle",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "centre_sante",
                    models.ForeignKey(
                        help_text="Centre de santé où la prestation a été effectuée",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestations_pharmacie",
                        to="centres.centresante",
                    ),
                ),
                (
                    "medicaments_utilises",
                    models.ManyToManyField(
                        related_name="prestations_pharmacie",
                        through="prestations.MedicamentUtilise",
                        to="prestations.medicament",
                    ),
                ),
                (
                    "mutualiste",
                    models.ForeignKey(
                        help_text="Mutualiste bénéficiant de la prestation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestations_pharmacie",
                        to="mutualistes.mutualiste",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        help_text="Prescription associée",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestations_pharmacie",
                        to="prestations.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestation Pharmacie",
                "verbose_name_plural": "Prestations Pharmacie",
                "ordering": ["-date_prestation"],
            },
        ),
        migrations.CreateModel(
            name="PrestationLunetterie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_prestation",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date et heure de la prestation"
                    ),
                ),
                (
                    "forfait_verres_et_montures",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Forfait pour les verres et montures",
                        max_digits=10,
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total de la prestation (forfait)",
                        max_digits=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description de la prestation", null=True
                    ),
                ),
                (
                    "centre_sante",
                    models.ForeignKey(
                        help_text="Centre de santé où la prestation est effectuée",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestations_lunetterie",
                        to="centres.centresante",
                    ),
                ),
                (
                    "mutualiste",
                    models.ForeignKey(
                        help_text="Mutualiste bénéficiant de la prestation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestations_lunetterie",
                        to="mutualistes.mutualiste",
                    ),
                ),
                (
                    "prise_en_charge",
                    models.ForeignKey(
                        help_text="Prise en charge associée à cette prestation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestations_lunetterie",
                        to="prestations.priseencharge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_prestation", models.DateTimeField(auto_now_add=True)),
                ("montant_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "montant_pris_en_charge",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tiers_payant", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("statut_validation", models.BooleanField(default=False)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                (
                    "centre_sante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centres.centresante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestation réalisée",
                "verbose_name_plural": "Prestations réalisées",
                "ordering": ["-date_prestation"],
            },
        ),
    ]
