# Generated by Django 4.1.7 on 2024-12-20 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prestations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestation",
            name="medecin_traitant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prestation",
            name="prestation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prestation_realisee",
                to="prestations.listedesprestations",
            ),
        ),
        migrations.AddField(
            model_name="prestation",
            name="prise_en_charge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prestations",
                to="prestations.priseencharge",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="prise_en_charge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="prestations.priseencharge",
            ),
        ),
        migrations.AddField(
            model_name="medicamentutilise",
            name="medicament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="utilisations_medicaments",
                to="prestations.medicament",
            ),
        ),
        migrations.AddField(
            model_name="medicamentutilise",
            name="prestation_pharmacie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="utilisations",
                to="prestations.prestationpharmacie",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="medicamentutilise",
            unique_together={("prestation_pharmacie", "medicament")},
        ),
    ]
