# Generated by Django 4.1.7 on 2025-01-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listedesprestations",
            name="tarif_standard",
            field=models.IntegerField(
                blank=True, help_text="Tarif standard", null=True
            ),
        ),
    ]
