# Generated by Django 4.1.7 on 2025-01-26 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0004_mutualiste_mutualistes_numero__6b1981_idx_and_more"),
        ("prestations", "0003_alter_listedesprestations_tarif_standard"),
    ]

    operations = [
        migrations.AddField(
            model_name="priseencharge",
            name="beneficiaire",
            field=models.ForeignKey(
                blank=True,
                help_text="Bénéficiaire concerné par cette prise en charge, s'il ne s'agit pas du mutualiste",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prises_en_charge",
                to="mutualistes.beneficiaire",
            ),
        ),
    ]
