# Generated by Django 4.1.7 on 2025-02-01 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("centres", "0004_medecintraitant"),
        ("prestations", "0004_priseencharge_beneficiaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestation",
            name="medecin_traitant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="centres.medecintraitant",
            ),
        ),
    ]
