# Generated by Django 4.1.7 on 2025-02-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0005_alter_prestation_medecin_traitant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestation",
            name="date_validation",
            field=models.DateField(blank=True, null=True),
        ),
    ]
