# Generated by Django 4.1.7 on 2025-02-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0006_alter_prestation_date_validation"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestation",
            name="montant_moderateur",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="prestation",
            name="date_validation",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
