# Generated by Django 4.1.7 on 2025-02-05 19:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("centres", "0004_medecintraitant"),
        ("mutualistes", "0006_mutualisteliste_and_more"),
        ("prestations", "0007_prestation_montant_moderateur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hospitalisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_admission", models.DateField(auto_now_add=True)),
                ("date_sortie", models.DateField(blank=True, null=True)),
                ("motif_hospitalisation", models.TextField(blank=True, null=True)),
                (
                    "fichier_hospitalisation",
                    models.FileField(
                        blank=True, null=True, upload_to="resultats_hospitalisation/"
                    ),
                ),
                (
                    "statut_prise_en_charge",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("validee", "Validée"),
                            ("refusee", "Refusée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "montant_prise_en_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("duree_validite", models.PositiveIntegerField(default=0)),
                (
                    "centre_sante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centres.centresante",
                    ),
                ),
                (
                    "mutualiste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospitalisations",
                        to="mutualistes.mutualiste",
                    ),
                ),
                (
                    "prise_en_charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestationshospi",
                        to="prestations.priseencharge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamenMedical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_prescription",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("date_realisation", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("realise", "Réalisé"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("resultat_texte", models.TextField(blank=True, null=True)),
                (
                    "fichier_resultat",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resultats_examens/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "centre_sante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="centres.centresante",
                    ),
                ),
                (
                    "mutualiste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examens",
                        to="mutualistes.mutualiste",
                    ),
                ),
                (
                    "prise_en_charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestationsexam",
                        to="prestations.priseencharge",
                    ),
                ),
                (
                    "type_examen",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prestations.listedesprestations",
                    ),
                ),
            ],
        ),
    ]
