# Generated by Django 4.1.7 on 2025-02-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "prestations",
            "0009_medicament_code_medicament_dci_medicament_molecule_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="medicament",
        ),
        migrations.AddField(
            model_name="prescription",
            name="medicament",
            field=models.ManyToManyField(
                related_name="prescriptions", to="prestations.medicament"
            ),
        ),
    ]
