# Generated by Django 4.1.7 on 2025-02-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0010_remove_prescription_medicament_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="montant",
        ),
        migrations.AddField(
            model_name="prescription",
            name="posologie",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
