# Generated by Django 4.1.7 on 2025-02-06 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0011_remove_prescription_montant_prescription_posologie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="medicament",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="posologie",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="quantite_prescrite",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="substitution_possible",
        ),
        migrations.AddField(
            model_name="prescription",
            name="code_prescription",
            field=models.CharField(
                editable=False,
                help_text="Code matricule généré automatiquement",
                max_length=9,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="date_prescription",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="MedicamentPrescris",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_prescrite", models.PositiveIntegerField()),
                ("posologie", models.CharField(blank=True, max_length=255, null=True)),
                ("substitution_possible", models.BooleanField(default=False)),
                (
                    "medicament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="prestations.medicament",
                    ),
                ),
                (
                    "prestation_prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicaments_prescris",
                        to="prestations.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Médicament Prescrit",
                "verbose_name_plural": "Médicaments Prescrits",
                "unique_together": {("prestation_prescription", "medicament")},
            },
        ),
    ]
