# Generated by Django 4.1.7 on 2025-02-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0012_remove_prescription_medicament_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("realise", "Réalisé"),
                    ("annule", "Annulé"),
                    ("facture", "facturé"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
