# Generated by Django 4.1.7 on 2025-02-06 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0013_prescription_statut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examenmedical",
            name="prise_en_charge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examens",
                to="prestations.priseencharge",
            ),
        ),
    ]
