# Generated by Django 4.1.7 on 2025-02-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0014_alter_examenmedical_prise_en_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamentprescris",
            name="medicament_substitue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substitutions",
                to="prestations.medicament",
            ),
        ),
    ]
