# Generated by Django 4.1.7 on 2025-02-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0017_priseencharge_medecin_traitant"),
    ]

    operations = [
        migrations.CreateModel(
            name="NaturePriseEnCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        help_text="Nature de la prise en charge",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["nature"],
            },
        ),
        migrations.AddField(
            model_name="priseencharge",
            name="nature",
            field=models.ForeignKey(
                help_text="Le mutualiste ayant cette nature de prise en charge",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="natureprises_en_charge",
                to="prestations.naturepriseencharge",
            ),
        ),
    ]
