# Generated by Django 4.1.7 on 2025-02-13 20:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0018_naturepriseencharge_priseencharge_nature"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestationlunetterie",
            name="fichier_resultat",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resultats_optique/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="prestationlunetterie",
            name="motif_refus",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prestationlunetterie",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("validee", "Validée"),
                    ("refusee", "Refusée"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prestationlunetterie",
            name="prise_en_charge",
            field=models.ForeignKey(
                blank=True,
                help_text="Prise en charge associée à cette prestation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prestations_lunetterie",
                to="prestations.priseencharge",
            ),
        ),
    ]
