# Generated by Django 4.1.7 on 2025-02-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0019_prestationlunetterie_fichier_resultat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestationlunetterie",
            name="prestation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prestations.listedesprestations",
            ),
        ),
    ]
