# Generated by Django 4.1.7 on 2025-02-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0021_prestationlunetterie_medecin_traitant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalisation",
            name="montant_prise_en_charge",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medicament",
            name="cout_unitaire",
            field=models.IntegerField(
                blank=True, help_text="Coût unitaire du médicament", null=True
            ),
        ),
        migrations.AlterField(
            model_name="medicamentutilise",
            name="cout_unitaire",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prestation",
            name="montant_moderateur",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prestation",
            name="montant_pris_en_charge",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prestation",
            name="montant_total",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prestationlunetterie",
            name="forfait_verres_et_montures",
            field=models.IntegerField(
                blank=True, help_text="Forfait pour les verres et montures", null=True
            ),
        ),
        migrations.AlterField(
            model_name="prestationlunetterie",
            name="montant_total",
            field=models.IntegerField(
                blank=True,
                help_text="Montant total de la prestation (forfait)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="prestationpharmacie",
            name="montant_total",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prestationpharmacie",
            name="part_mutualiste",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prestationpharmacie",
            name="part_mutuelle",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
