# Generated by Django 4.2.19 on 2025-03-24 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0020_alter_beneficiaire_photo"),
        ("prestations", "0022_alter_hospitalisation_montant_prise_en_charge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examenmedical",
            name="beneficiaire",
            field=models.ForeignKey(
                blank=True,
                help_text="Bénéficiaire concerné par cette prise en charge, s'il ne s'agit pas du mutualiste",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ex",
                to="mutualistes.beneficiaire",
            ),
        ),
        migrations.AddField(
            model_name="hospitalisation",
            name="beneficiaire",
            field=models.ForeignKey(
                blank=True,
                help_text="Bénéficiaire concerné par cette prise en charge, s'il ne s'agit pas du mutualiste",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospi",
                to="mutualistes.beneficiaire",
            ),
        ),
    ]
