# Generated by Django 4.2.19 on 2025-03-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0023_examenmedical_beneficiaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examenmedical",
            name="prestations",
            field=models.ManyToManyField(
                blank=True, related_name="examens", to="prestations.prestation"
            ),
        ),
        migrations.AddField(
            model_name="hospitalisation",
            name="prestations",
            field=models.ManyToManyField(
                blank=True, related_name="hospitalisations", to="prestations.prestation"
            ),
        ),
    ]
