# Generated by Django 4.2.19 on 2025-03-25 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prestations", "0024_examenmedical_prestations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examenmedical",
            name="prestations",
        ),
    ]
