# Generated by Django 4.2.19 on 2025-03-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mutualistes", "0020_alter_beneficiaire_photo"),
        ("prestations", "0025_remove_examenmedical_prestations"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestationlunetterie",
            name="beneficiaire",
            field=models.ForeignKey(
                blank=True,
                help_text="Bénéficiaire concerné par cette prise en charge, s'il ne s'agit pas du mutualiste",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="optik",
                to="mutualistes.beneficiaire",
            ),
        ),
        migrations.AddField(
            model_name="prestationpharmacie",
            name="beneficiaire",
            field=models.ForeignKey(
                blank=True,
                help_text="Bénéficiaire concerné par cette prise en charge, s'il ne s'agit pas du mutualiste",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pharm",
                to="mutualistes.beneficiaire",
            ),
        ),
    ]
