# Generated by Django 4.1.7 on 2025-01-26 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mutualistes", "0004_mutualiste_mutualistes_numero__6b1981_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieAffection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de la catégorie (ex: Chronique, Aiguë, etc.)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description de la catégorie", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie d'affection",
                "verbose_name_plural": "Catégories d'affection",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Ordonnance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_emission",
                    models.DateField(
                        auto_now_add=True, help_text="Date d'émission de l'ordonnance"
                    ),
                ),
                (
                    "renouvelable",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si l'ordonnance est renouvelable",
                    ),
                ),
                (
                    "periodicite",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Périodicité du renouvellement (en jours)",
                        null=True,
                    ),
                ),
                (
                    "valide_jusquau",
                    models.DateField(
                        blank=True,
                        help_text="Date limite pour renouveler l'ordonnance",
                        null=True,
                    ),
                ),
                (
                    "mutualiste",
                    models.ForeignKey(
                        help_text="Mutualiste pour lequel l'ordonnance est émise",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordonnances",
                        to="mutualistes.mutualiste",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoriqueCodeMatricule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ancien_code",
                    models.CharField(help_text="Ancien code matricule", max_length=9),
                ),
                (
                    "date_changement",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date du changement de code matricule",
                    ),
                ),
                (
                    "mutualiste",
                    models.ForeignKey(
                        help_text="Mutualiste associé à ce code matricule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_codes",
                        to="mutualistes.mutualiste",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodeAffection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique de l'affection (ex: A001, C123, etc.)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de l'affection (ex: Hypertension, Diabète)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de l'affection",
                        null=True,
                    ),
                ),
                (
                    "date_creation",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date de création du code d'affection",
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        help_text="Catégorie associée à cette affection",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affections",
                        to="configurations.categorieaffection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code d'affection",
                "verbose_name_plural": "Codes d'affection",
                "ordering": ["code"],
            },
        ),
    ]
