# Generated by Django 4.2.19 on 2025-03-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordonnance",
            options={
                "ordering": ["-date_emission"],
                "verbose_name": "Ordonnance",
                "verbose_name_plural": "Ordonnances",
            },
        ),
        migrations.AddField(
            model_name="codeaffection",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Dernière mise à jour du code d'affection"
            ),
        ),
        migrations.AddField(
            model_name="ordonnance",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Dernière mise à jour de l'ordonnance"
            ),
        ),
    ]
