# Generated by Django 4.1.7 on 2024-12-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facturations", "0001_initial"),
        ("prestations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="prises_en_charge",
            field=models.ManyToManyField(
                help_text="Prises en charge incluses dans la facture",
                related_name="factures",
                to="prestations.priseencharge",
            ),
        ),
    ]
