# Generated by Django 4.1.7 on 2025-02-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "facturations",
            "0003_facture_intitule_facture_facture_numero_facture_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="intitule_facture",
            field=models.CharField(
                editable=False,
                help_text="Intitulé de la facture sous la forme 'Mois Année'",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="numero_facture",
            field=models.CharField(
                editable=False,
                help_text="Numéro unique de la facture au format MMYYYY pour chaque centre",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="facture",
            constraint=models.UniqueConstraint(
                fields=("centre", "numero_facture"),
                name="unique_numero_facture_par_centre",
            ),
        ),
        migrations.AddConstraint(
            model_name="facture",
            constraint=models.UniqueConstraint(
                fields=("centre", "intitule_facture"),
                name="unique_intitule_facture_par_centre",
            ),
        ),
    ]
