# Generated by Django 4.1.7 on 2025-02-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facturations", "0004_alter_facture_intitule_facture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="total_mutualiste",
            field=models.IntegerField(
                default=0, help_text="Montant total à la charge des mutualistes"
            ),
        ),
    ]
