# Generated by Django 4.1.7 on 2025-02-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facturations", "0005_alter_facture_total_mutualiste"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="total_general",
            field=models.IntegerField(
                default=0, help_text="Montant total de la facture"
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="total_mutuelle",
            field=models.IntegerField(
                default=0, help_text="Montant total pris en charge par la mutuelle"
            ),
        ),
    ]
