# Generated by Django 4.1.7 on 2025-02-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facturations", "0006_alter_facture_total_general_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remboursement",
            name="montant",
            field=models.IntegerField(
                blank=True, help_text="Montant remboursé en FCFA", null=True
            ),
        ),
    ]
