# Generated by Django 4.2.19 on 2025-03-27 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facturations", "0007_alter_remboursement_montant"),
    ]

    operations = [
        migrations.AddField(
            model_name="remboursement",
            name="justif",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="justif/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "png"]
                    )
                ],
            ),
        ),
    ]
